/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentRegistry } from "./StudentRegistry";
export * as factories from "./factories";
export { StudentRegistry__factory } from "./factories/StudentRegistry__factory";
