/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StudentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addStudent"
      | "getStudent"
      | "getTotalStudents"
      | "students"
      | "updateAttendance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AttendanceUpdated" | "StudentAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addStudent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAttendance",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "addStudent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStudent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAttendance",
    data: BytesLike
  ): Result;
}

export namespace AttendanceUpdatedEvent {
  export type InputTuple = [studentId: BigNumberish, present: boolean];
  export type OutputTuple = [studentId: bigint, present: boolean];
  export interface OutputObject {
    studentId: bigint;
    present: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudentAddedEvent {
  export type InputTuple = [
    studentId: BigNumberish,
    name: string,
    age: BigNumberish
  ];
  export type OutputTuple = [studentId: bigint, name: string, age: bigint];
  export interface OutputObject {
    studentId: bigint;
    name: string;
    age: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StudentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StudentRegistry;
  waitForDeployment(): Promise<this>;

  interface: StudentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addStudent: TypedContractMethod<
    [_name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;

  getStudent: TypedContractMethod<
    [_studentId: BigNumberish],
    [[string, bigint, boolean]],
    "view"
  >;

  getTotalStudents: TypedContractMethod<[], [bigint], "view">;

  students: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        name: string;
        age: bigint;
        present: boolean;
      }
    ],
    "view"
  >;

  updateAttendance: TypedContractMethod<
    [_studentId: BigNumberish, _present: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addStudent"
  ): TypedContractMethod<
    [_name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getStudent"
  ): TypedContractMethod<
    [_studentId: BigNumberish],
    [[string, bigint, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalStudents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        name: string;
        age: bigint;
        present: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateAttendance"
  ): TypedContractMethod<
    [_studentId: BigNumberish, _present: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AttendanceUpdated"
  ): TypedContractEvent<
    AttendanceUpdatedEvent.InputTuple,
    AttendanceUpdatedEvent.OutputTuple,
    AttendanceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StudentAdded"
  ): TypedContractEvent<
    StudentAddedEvent.InputTuple,
    StudentAddedEvent.OutputTuple,
    StudentAddedEvent.OutputObject
  >;

  filters: {
    "AttendanceUpdated(uint256,bool)": TypedContractEvent<
      AttendanceUpdatedEvent.InputTuple,
      AttendanceUpdatedEvent.OutputTuple,
      AttendanceUpdatedEvent.OutputObject
    >;
    AttendanceUpdated: TypedContractEvent<
      AttendanceUpdatedEvent.InputTuple,
      AttendanceUpdatedEvent.OutputTuple,
      AttendanceUpdatedEvent.OutputObject
    >;

    "StudentAdded(uint256,string,uint256)": TypedContractEvent<
      StudentAddedEvent.InputTuple,
      StudentAddedEvent.OutputTuple,
      StudentAddedEvent.OutputObject
    >;
    StudentAdded: TypedContractEvent<
      StudentAddedEvent.InputTuple,
      StudentAddedEvent.OutputTuple,
      StudentAddedEvent.OutputObject
    >;
  };
}
